# Generated by Django 6.0.7 on 2026-08-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_wishlist_created_at_wishlist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='role',
            field=models.CharField(choices=[('Participant', 'Participant'), ('Organizer', 'Organizer')], default='Participant', max_length=20),
        ),
    ]
